### ISSUE TITLE
Emails containing + cannot be searched

### ISSUE THREAD

**Issue by quest313** [SpartaSystems/holdmail#31]
##### Question/Issue Overview

Search by email fails to find results for emails containing + character

##### Expected Behavior

emails with a '+' character are returned

##### Current Behavior

No results are returned

##### Reproducible Sequence
1. Have hold capture email from someuser+s103@somewhere.com
2. Search for that email.

**Comment by kblief** [comment]
This appears to be an issue with the UI code.
