### ISSUE TITLE
Move to alternate UI framework

### ISSUE THREAD

**Issue by barryoneill** [SpartaSystems/holdmail#6]
The app is currently implemented in AngularJS 1, but as it approaches its sunset, we should investigate its replacement.

**Comment by barryoneill** [comment]
Current candidates for the new framework:

- React
- Vue.js
- Angular 2

**Comment by tsneed290** [comment]
After discussion, it was agreed to migrate the holdmail-ui-vue project into holdmail. 

Closing this ticket in lieu of #39.
