### ISSUE TITLE
Timeframe for Holdmail 2.0

### ISSUE THREAD

**Issue by johnament** [SpartaSystems/holdmail#60]
I've updated the release date for 2.0 to 1/26.  There's still several tickets in the 2.0 milestone that I'm not sure if we're going to resolve in this release.  I'd like to make a hard date for the release on 1/26, so please shout if anything needs to get done before hand.

@wreddin @vickiehwang @praveenaram @barryoneill @kblief @tsneed290

**Comment by barryoneill** [comment]
Any volunteer to take https://github.com/SpartaSystems/holdmail/issues/24 ?
With the vue changeover, it actually builds much better in Windows, but I
think there are Apache RAT pattern issues, and after 2 minutes of using
eclipse I gave up.   Maybe we could just stick a #helpwanted label on it
and punt to 2.1.

https://github.com/SpartaSystems/holdmail/issues/14 has been a rather large
endeavor, but I'm towards the end.   Not sure I'll get UI support in, but
at least the API should be usable.  I need a few more days, let me try and
schedule in some more time for it in the coming days - I'll make Monday my
cutoff.


Barry.

**Comment by johnament** [comment]
I'd rather punt on #24, I have access to a windows VM but not eclipse. and would need to set it up and see what is failing.

#14 is a cool idea, I know our internal use cases don't push for it but I can see others wanting such a thing (emailing shipping invoices, and other attachments).

**Comment by barryoneill** [comment]
From a backend POV, #14 is the bulk of 2.0 (it fixes many i18n issues too), and I'm also finalizing a breaking API change (dropping 'messageRaw' attribute from /rest/messages/ID). 

It's pretty much done. If I don't get to the frontend, I'll punt that to a 2.1 ticket.

**Comment by barryoneill** [comment]
Issue #14 is closed.  I've closed or bumped all other 2.0 milestone issues.  

I was hoping to get to some UI tweaking, but I guess it can wait.  There's some sluggishness around the tabs in the message detail view, if I get time this week I'll look into it, but it can also wait.

**Comment by johnament** [comment]
@barryoneill I think we're all set right?  I finally have my laptop back, so I'm going to plan to do the release by this Friday.

**Comment by barryoneill** [comment]
Yes, all dev tasks for milestone 2.0 are done.  There's a 2.0 docs task open; if I don't get to it by Friday, feel free to find a volunteer.
