### ISSUE TITLE
Mails are stored with insufficient date precision

### ISSUE THREAD

**Issue by barryoneill** [SpartaSystems/holdmail#8]
Right now, when using MySQL, the default timestamp precision used:

https://github.com/SpartaSystems/holdmail/blob/master/src/main/resources/db/migration/V0.1_001__init.sql#L7

results in nothing smaller than seconds being stored.  This isn't good enough for high volume test runs, and should be expanded to millisecond, probably microsecond resolution.

**Comment by barryoneill** [comment]
To verify, in a mysql environment, see that the mail list returned from

`GET /rest/messages`

Has millisecond precision in the 'receivedDate' attribute. (previously, messages would have zeros at the last three positions).

**Comment by praveenaram** [comment]
QA has verified from our test runs - we now are able to correctly retrieve emails with this fix for timestamp precision.
